### ISSUE TITLE
Adapting the lib for RGBW leds

### ISSUE THREAD

**Issue by jgastonraoul** [PaulStoffregen/WS2812Serial#5]
Is there a way to adapt the library for RGBW LEDs ? I've tried to do so but I'm not able to turn on white LEDs (and blue LED seems to be mixed with white). Any idea?

**Comment by PaulStoffregen** [comment]
let's discuss this on the forum thread
https://forum.pjrc.com/threads/49209-Non-blocking-library-for-RGBW-Neopixels

**Comment by azzeloof** [comment]
I believe I found a working solution, see Pull Request #7 
(Thanks @jgastonraoul for the edits you posted in the forum!)

**Comment by mkalkbrenner** [comment]
I think RGBW is fully supported and this issue could be closed.
